### ISSUE TITLE
Add plugin to official plugin list

### ISSUE THREAD

**Issue by htcfreek** [anthony81799/PowerToysRun-RDP#1]
There is a document that lists third-party plugins for PT Run. It is linked from the PT Settings Ui.

File: https://github.com/microsoft/PowerToys/blob/main/doc%2FthirdPartyRunPlugins.md

I suggest to add your plugin on the list.

**Comment by anthony81799** [comment]
> There is a document that lists third-party plugins for PT Run. It is linked from the PT Settings Ui.
> 
> File: https://github.com/microsoft/PowerToys/blob/main/doc%2FthirdPartyRunPlugins.md
> 
> I suggest to add your plugin on the list.

Thanks for letting me know. I've added RDP to the file and created a pull request.
