### ISSUE TITLE
Support for the modern 'Remote Desktop' app?

### ISSUE THREAD

**Issue by philosophicles** [anthony81799/PowerToysRun-RDP#15]
I use the more modern "Microsoft Remote Desktop" app available from the Windows Store: https://apps.microsoft.com/detail/9wzdncrfj3ps

Is there any way this could be supported by this plugin? I have some tens of connections saved in there but the plugin currently does not see them. In principle this is a _fantastic_ plugin for PowerToys.

**Comment by 8LWXpg** [comment]
I think it worth a separate plugin, so I made one [RemoteDesktopUWP](https://github.com/8LWXpg/PowerToysRun-RemoteDesktopUWP).

**Comment by philosophicles** [comment]
@8LWXpg thank you! Works a treat. Closing this issue.

**Comment by htcfreek** [comment]
@8LWXpg 
Is your plugin listet on the official third party plugins list? Would make sense to do so and have both plugins listed.

**Comment by 8LWXpg** [comment]
@htcfreek I totally forgot that, thanks for reminding.
