### ISSUE TITLE
Version information wrong in file properties

### ISSUE THREAD

**Issue by htcfreek** [anthony81799/PowerToysRun-RDP#16]
The version information of the DLL file are wrong.

Please note that we are working on an improvement for the plugin manager user interface that will show the `File version` as plugin version.

![image](https://github.com/user-attachments/assets/cce98272-49a1-4c03-af46-6e2a4c196370)

![image](https://github.com/user-attachments/assets/0d738288-99a4-4fc6-a302-059b754c08c2)

**Comment by anthony81799** [comment]
This issue has been resolved.
